[project]
name = "qqq-ingest"
version = "0.0.1"
requires-python = ">=3.10"
dependencies = ["pandas", "pyarrow", "pytz", "python-dateutil", "tqdm", "numpy"]

[tool.setuptools.packages.find]
where = ["src"]
